name: Publish to PyPI

on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install bump2version

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Parse commit message for bump type
        id: detect_bump
        run: |
            if echo "${{ github.event.head_commit.message }}" | grep -qE '#major|!major'; then
              echo "bump_type=major" >> $GITHUB_OUTPUT
            elif echo "${{ github.event.head_commit.message }}" | grep -qE '#minor|!minor'; then
              echo "bump_type=minor" >> $GITHUB_OUTPUT
            else
              echo "bump_type=patch" >> $GITHUB_OUTPUT
            fi

      - name: Bump version (Patch)
        run: bump2version ${{ steps.detect_bump.outputs.bump_type }}

      - name: Push version bump
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          branch: main
          # Wichtig: Verhindere Endlosschleife
          commit_message: "Bump version [skip ci]"

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_KEY }}
        run: twine upload dist/*

      - name: Checkout develop
        uses: actions/checkout@v4
        with:
          ref: develop
          # Wichtig: Fetch auch main für den Merge
          fetch-depth: 0

      - name: Merge main into develop
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git merge origin/main --no-edit
          git push origin develop
